{application,nitrogen,
             [{description,"My Nitrogen Web Project"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nitrogen_app,[]}},
              {env,[]},
              {modules,[game,game_master,game_server,game_sup,index,
                        nitrogen_app,nitrogen_mochiweb,nitrogen_sup,pl,play,
                        player,word_server]}]}.
